theme = "mytheme"

[editor]
line-number = "relative"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'<' = '>'
'"' = '"'
"'" = "'"

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]
