#!/usr/bin/env bash
pkill waybar

export XDG_CURRENT_DESKTOP=river
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=river
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export INPUT_METHOD=fcitx
export SDL_IM_MODULE=fcitx

systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE
systemctl --user start xdg-desktop-portal-wlr.service &
systemctl --user start xdg-desktop-portal.service &

swaybg -i $HOME/pictures/wallpapers/wallpaper4.* &

fcitx5 &
waybar &
brightnessctl -d intel_backlight set 0 && brightnessctl -d tpacpi::kbd_backlight set 2 &

#startup
riverctl xcursor-theme Bibata-Modern-Ice
tileInit() {
rivercarro &
riverctl default-layout rivercarro
riverctl send-layout-cmd rivercarro "main-count 1"
riverctl send-layout-cmd rivercarro "main-ratio 0.5"
riverctl send-layout-cmd rivercarro "width-ratio 1"
riverctl send-layout-cmd rivercarro "no-smart-gaps"
riverctl send-layout-cmd rivercarro "no-smart-gaps"
riverctl send-layout-cmd rivercarro "inner-gaps 8"
riverctl send-layout-cmd rivercarro "outer-gaps 5"
riverctl send-layout-cmd rivercarro "main-location left"
}
riverctl focus-follows-cursor always

riverctl border-color-unfocused 0x000000
riverctl border-color-focused 0x000055
riverctl border-width 1

riverctl rule-add '*' float=false

#input lang
riverctl keyboard-layout no

alt="Mod1"
altgr="Mod5"
super="Super"

#rules
riverctl rule-add -app-id foot tags 1
riverctl rule-add -app-id librewolf tags 2
riverctl rule-add -app-id steam tags 4
riverctl rule-add -app-id librewolf fullscreen

riverctl declare-mode sound
riverctl map sound $alt n enter-mode normal
riverctl map normal $alt s enter-mode sound
riverctl map sound  $alt p spawn "playerctl play-pause & riverctl enter-mode normal"
riverctl map sound  $alt+Shift l spawn "playerctl next" 
riverctl map sound  $alt+Shift h spawn "playerctl previous"
riverctl map sound  $alt+Shift k spawn "playerctl volume 0.1+"
riverctl map sound  $alt+Shift j spawn "playerctl volume 0.1-"
riverctl map sound  $alt k spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+"
riverctl map sound  $alt j spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%-"
riverctl map sound  $alt m spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle & riverctl enter-mode normal" 
riverctl map sound $alt l spawn "playerctl position 10+"
riverctl map sound $alt h spawn "playerctl position 10-"

riverctl declare-mode bright
riverctl map bright $alt n enter-mode normal 
riverctl map normal $alt b enter-mode bright
riverctl map bright $alt k spawn "brightnessctl set 10%+"
riverctl map bright $alt j spawn "brightnessctl set 10%-"
riverctl map bright $alt+Shift j spawn "brightnessctl -d tpacpi::kbd_backlight set 1+"
riverctl map bright $alt+Shift k spawn "brightnessctl -d tpacpi::kbd_backlight set 1-"

#map aka binds
#common lanching apps etc
riverctl map normal Mod5 Space spawn "waypaper"
# riverctl map normal $alt s spawn "systemctl suspend"
# riverctl map normal $alt+Shift s spawn "waylock"
riverctl map normal $alt t spawn foot
riverctl map normal $super s spawn "systemctl suspend"
riverctl map normal $super l spawn "waylock"
riverctl map normal $alt f toggle-fullscreen
riverctl map normal $alt q close
riverctl map normal $altgr g spawn 'grim -g "$(slurp)" ~/pictures/$(date +%M:%H_%d-%m-%Y).png | wl-copy'
riverctl map normal $alt Space spawn "bemenu-run -l 10"
riverctl map normal $alt+Shift E exit
riverctl map normal $altgr f toggle-float
riverctl map normal $super+Shift s spawn "mullvad-exclude DRI_PRIME=0 steam"
riverctl map normal $super+Shift m spawn "mullvad-exclude prismlauncher"

#playerctl wpctl

#brightness ctl

riverctl map normal $alt+Shift h focus-output left 
riverctl map normal $alt+Shift l send-to-output right

#navigation
riverctl map normal $super h focus-view left
riverctl map normal $super l focus-view right
riverctl map normal $super j focus-view down
riverctl map normal $super k focus-view up

#snap FLOATING windows
riverctl map normal $altgr h snap left
riverctl map normal $altgr l snap right
riverctl map normal $altgr j snap down
riverctl map normal $altgr k snap up
riverctl map normal $super+shift h focus-output left
riverctl map normal $super+shift j focus-output down
riverctl map normal $super+shift k focus-output upup
riverctl map normal $super+shift l focus-output right
riverctl map normal $super+$mod h send-to-output left
riverctl map normal $super+$mod j send-to-output down
riverctl map normal $super+$mod k send-to-output upup
riverctl map normal $super+$mod l send-to-output right
riverctl map normal $super+Shift h send-layout-cmd rivercarro "main-ratio +0.1"
riverctl map normal $super+Shift l send-layout-cmd rivercarro "main-ratio -0.1"

#switch what tag you see
riverctl map normal $alt+Shift 1 toggle-focused-tags 1
riverctl map normal $alt+Shift 2 toggle-focused-tags 2
riverctl map normal $alt+Shift 3 toggle-focused-tags 4
riverctl map normal $alt+Shift 4 toggle-focused-tags 8
riverctl map normal $alt+Shift 5 toggle-focused-tags 16
riverctl map normal $alt+Shift 6 toggle-focused-tags 32
riverctl map normal $alt+Shift 7 toggle-focused-tags 64
riverctl map normal $alt+Shift 8 toggle-focused-tags 128
riverctl map normal $alt+Shift 9 toggle-focused-tags 256
riverctl map normal $alt+Shift 0 toggle-focused-tags 512

riverctl map normal $altgr+Shift 1 set-view-tags 1
riverctl map normal $altgr+Shift 2 set-view-tags 2
riverctl map normal $altgr+Shift 3 set-view-tags 4
riverctl map normal $altgr+Shift 4 set-view-tags 8
riverctl map normal $altgr+Shift 5 set-view-tags 16
riverctl map normal $altgr+Shift 6 set-view-tags 32
riverctl map normal $altgr+Shift 7 set-view-tags 64
riverctl map normal $altgr+Shift 8 set-view-tags 128
riverctl map normal $altgr+Shift 9 set-view-tags 256
riverctl map normal $altgr+Shift 0 set-view-tags 512
#assigning tag to window

riverctl map normal $super 1 set-focused-tags 1
riverctl map normal $super 2 set-focused-tags 2
riverctl map normal $super 3 set-focused-tags 4
riverctl map normal $super 4 set-focused-tags 8
riverctl map normal $super 5 set-focused-tags 16
riverctl map normal $super 6 set-focused-tags 32
riverctl map normal $super 7 set-focused-tags 64
riverctl map normal $super 8 set-focused-tags 128
riverctl map normal $super 9 set-focused-tags 256
riverctl map normal $super 0 set-focused-tags 512

tileInit
riverctl focus-output next
tileInit

wlr-randr --output HDMI-A-1 --pos 0,0
wlr-randr --output eDP-1 --pos 1920,0
