#!/usr/bin/env bash
export \
XDG_CURRENT_DESKTOP=river \
XDG_SESSION_TYPE=wayland \
XDG_SESSION_DESKTOP=river \
GTK_IM_MODULE=fcitx \
QT_IM_MODULE=fcitx \
XMODIFIERS=@im=fcitx \
INPUT_METHOD=fcitx \
SDL_IM_MODULE=fcitx

systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE
systemctl --user start xdg-desktop-portal-wlr.service &
systemctl --user start xdg-desktop-portal.service &

swaybg -i $HOME/Wallpapers/wallpaper1.* --mode fill &

#wlr-randr --output eDP-1 --off

fcitx5 &
pkill waybar
waybar &
brightnessctl -d intel_backlight set 0 && brightnessctl -d tpacpi::kbd_backlight set 2 &

r(){
  riverctl "$@"
  }

#startup
r xcursor-theme Bibata-Modern-Ice
tileInit() {
rivercarro &
r default-layout rivercarro
r send-layout-cmd rivercarro "main-count 1"
r send-layout-cmd rivercarro "main-ratio 0.5"
r send-layout-cmd rivercarro "width-ratio 1"
r send-layout-cmd rivercarro "no-smart-gaps"
r send-layout-cmd rivercarro "no-smart-gaps"
r send-layout-cmd rivercarro "inner-gaps 8"
r send-layout-cmd rivercarro "outer-gaps 5"
r send-layout-cmd rivercarro "main-location left"
}
tileInit
r focus-follows-cursor always
r hide-cursor when-typing enabled
r hide-cursor timeout 2000
r set-cursor-warp on-output-change

r border-color-unfocused 0x000000
r border-color-focused 0x000055
r border-width 1

# r rule-add '*' float=false

#input lang
r keyboard-layout no

a="Mod1"
g="Mod5"
s="Super"

#cuz normal is awfully long for waybar
r declare-mode n
r enter-mode n

r declare-mode s
r map n $s s enter-mode s
r map s None escape enter-mode n
r map s None m spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
r map s None space spawn "playerctl play-pause"
r map s None h spawn "playerctl previous"
r map s None j spawn "playerctl volume 0.1-"
r map s None k spawn "playerctl volume 0.1+"
r map s None l spawn "playerctl next"
r map s None+Shift h spawn "playerctl position 5%-"
r map s None+Shift j spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%-"
r map s None+Shift k spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+"
r map s None+Shift l spawn "playerctl position 5%+"

r declare-mode b
r map n $s b enter-mode b
r map b None escape enter-mode n
r map b None j spawn "brightnessctl set 10%-"
r map b None k spawn "brightnessctl set 10%+"

tags=(1 2 4 8 16 32 64 128 256 512)
keys=(1 2 3 4 5 6 7 8 9 0)

r declare-mode w
r map n $s w enter-mode w
r map w None escape enter-mode n
r map w None f toggle-float 
r map w None q close

r map w None h focus-view left
r map w None j focus-view down 
r map w None k focus-view up 
r map w None l focus-view right

r map w None+Shift h swap left 
r map w None+Shift j swap down 
r map w None+Shift k swap up 
r map w None+Shift l swap right

r map w $g h resize horizontal -100
r map w $g j resize vertical +100
r map w $g k resize vertical -100
r map w $g l resize horizontal +100

r map w $s h send-layout-cmd rivercarro "main-ratio -0.1"
r map w $s j send-layout-cmd rivercarro "main-count -1"
r map w $s k send-layout-cmd rivercarro "main-count +1"
r map w $s l send-layout-cmd rivercarro "main-ratio +0.1"
r map w None c send-layout-cmd rivercarro "main-location-cycle top,bottom,left,right"

r map w $a h snap left
r map w $a j snap down
r map w $a k snap up
r map w $a l snap right
r map w $a+Shift h move left +100
r map w $a+Shift j move down +100
r map w $a+Shift k move down -100
r map w $a+Shift l move left -100

for i in "${!keys[@]}"; do
  key=${keys[$i]}
  tag=${tags[$i]}
  r map w "None" "$key" set-view-tags "$tag"
  r map w "$a" "$key" toggle-view-tags "$tag"
  r map w "$s" "$key" spawn "riverctl set-focused-tags $tag; riverctl enter-mode n"
  done

r map n $s g spawn 'grim -g \"$(slurp)\" - | tee ~/Pictures/screenshot-$(date +%F_%H-%M-%S).png | wl-copy'
r map n $a+Shift e exit
r map n $a Space spawn "fuzzel"
r map n $g Space spawn "waylock"
r map n $a t spawn "foot"
r map n $a b spawn "librewolf"

r map n $s f toggle-fullscreen
r map n $s l spawn "systemctl suspend"

r map n $s h focus-view left
r map n $s l focus-view right
r map n $s j focus-view down
r map n $s k focus-view up

r map n $s+Shift h focus-output left
r map n $s+Shift j focus-output down
r map n $s+Shift k focus-output up
r map n $s+Shift l focus-output right


for i in "${!keys[@]}"; do
  key=${keys[$i]}
  tag=${tags[$i]}
  r map n "$s" "$key" set-focused-tags "$tag"
  r map n "$s+Shift" "$key" toggle-focused-tags "$tag"
done
